### PR TITLE
Swift Package Manager

### PR DESCRIPTION
**Pull request by ZevEisenberg**
Way of the future

### CODE REVIEW

**Comment by DomAmato** [comment]
This resolved for me and properly grabbed the files.
 `.package(url: "https://github.com/Rightpoint/BonMot.git", .branch("feature/zeveisenberg/swiftpm")),`

Let me know if there is more to testing this than that but everything seems to be rendering as expected

**Comment by rainhead** [comment]
Thanks for maintaining the branch while this PR is open.

**Comment by chrisballinger** [comment]
The status checks are stale, going to close and reopen.

**Comment by j-f1** [comment]
@chrisballinger/@ZevEisenberg can you re-tag `5.5` as `5.5.0`? Xcode won’t pick it up otherwise.

**Pull request merged**
