### PR TITLE
Add lineBreakStrategy paragraph attribute

### PR DESCRIPTION
**Pull request by OhKanghoon**
Add lineBreakStrategy paragraph attribute

### CODE REVIEW

**Comment by OhKanghoon** [comment]
Hi @ZevEisenberg 
Would you consider merging and release this PR?

**Review by ZevEisenberg — APPROVED** [review]

**Comment by ZevEisenberg** [comment]
@OhKanghoon thanks for your contribution! I'll cut a release.

**Comment by ZevEisenberg** [comment]
https://github.com/Rightpoint/BonMot/releases/tag/6.1.0

**Comment by ZevEisenberg** [comment]
Yep, just noticed I messed that up. I'll do it later today. It will probably be 6.1.1 so I don't break existing tags.

**Comment by ZevEisenberg** [comment]
Sorry for the delay. Working on coordinating with people who need to refresh CocoaPods access tokens. If you need it sooner, please point your Podfile at the master branch or use SPM if that's an option.

**Comment by ZevEisenberg** [comment]
Released!

**Pull request merged**
