### PR TITLE
Swift 5

### PR DESCRIPTION
**Pull request by ZevEisenberg**
- [x] add build step for Xcode 10.2 once it is available on CircleCI. Can swap it in for one of the older Xcode 9 builds.

### CODE REVIEW

**Comment by chrisballinger** [comment]
Looks good to me! Have you seen any ETA on Circle's Xcode 10.2 support?

**Comment by ZevEisenberg** [comment]
Nope. They’re usually within a week or so, I think? But I’ll probably wait to merge this until well into the beta cycle anyway.

**Comment by ZevEisenberg** [comment]
[Update on CircleCI Xcode 10.2 support](https://discuss.circleci.com/t/when-is-xcode-10-2-support-coming-up/28160/9). TL;DR: No firm date, because Xcode 10.2 requires macOS 10.14, which requires them to make some changes to their release process.

**Comment by chrisballinger** [comment]
@ZevEisenberg Thanks for the update! Eagerly awaiting Xcode 10.2... :)

**Comment by ZevEisenberg** [comment]
Xcode 10.2 beta is now available on CircleCI 
https://discuss.circleci.com/t/xcode-10-2-beta-3-image-released/28518

**Comment by ZevEisenberg** [comment]
Xcode 10.2 is the only one that's passing. Which is…good? (I think the scripts need to go back to passing the `SWIFT_VERSION` explicitly, because I bumped it to 5.0 in the project 🤦🏻‍♂️

**Pull request merged**
